### ISSUE TITLE
creating a  Gulp task for this package

### ISSUE THREAD

**Issue by masterbee** [nidorx/html-improved#1]
Hi @nidorx, first off this is a great package and I was wondering if there was any ambition to create a gulp task like the grunt version?

**Comment by nidorx** [comment]
https://www.npmjs.com/package/gulp-html-improved



![maxresdefault](https://user-images.githubusercontent.com/675430/66224135-89f76a00-e6ab-11e9-8c6a-b80aa2e65196.jpg)
